# Generated by Django 4.1.7 on 2023-03-24 17:03

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='약 이름')),
                ('efficacy', models.TextField(verbose_name='약 효과')),
            ],
            options={
                'verbose_name': '약 정보',
                'verbose_name_plural': '약 정보',
                'db_table': 'pill_tb',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
    ]
