# Generated by Django 4.1.7 on 2023-04-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pill", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pill",
            options={
                "ordering": ["-id"],
                "verbose_name": "약",
                "verbose_name_plural": "약",
            },
        ),
        migrations.AlterField(
            model_name="pill",
            name="efficacy",
            field=models.TextField(verbose_name="효과"),
        ),
        migrations.AlterField(
            model_name="pill",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="이름"),
        ),
    ]
